# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, help_text='Rendas para referência na carta de crédito', max_digits=9, verbose_name='Renda')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
            ],
            options={
                'ordering': ['income', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='interest')),
                ('income_max_sub', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Renda máxima para o máximo de subsídio')),
                ('income_min_sub', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Renda máxima para o mínimo de subsídio')),
                ('min_income', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Renda mínima')),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='simulator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='simulator.Simulator'),
        ),
    ]
