# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentConstant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sac', 'SAC'), ('price', 'PRICE')], max_length=4)),
                ('value', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
    ]
