# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_installmentconstant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentconstant',
            name='type',
            field=models.CharField(choices=[('sac', 'SAC'), ('price', 'PRICE')], max_length=5),
        ),
        migrations.AlterField(
            model_name='installmentconstant',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
