# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_auto_20180520_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Anúncios municipais',
                'verbose_name': 'Anúncio municipal',
            },
        ),
        migrations.CreateModel(
            name='ADNational',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Anúncios nacionais',
                'verbose_name': 'Anúncio nacional',
            },
        ),
        migrations.CreateModel(
            name='ADState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Anúncios estaduais',
                'verbose_name': 'Anúncio estadual',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('image', models.ImageField(upload_to='advertises/', verbose_name='Imagem')),
                ('url', models.URLField(verbose_name='Link destino')),
            ],
            options={
                'verbose_name_plural': 'Banners',
                'verbose_name': 'Banner',
            },
        ),
        migrations.AddField(
            model_name='adstate',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adstate_advertises', to='advertises.Banner', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='adstate',
            name='states',
            field=models.ManyToManyField(related_name='advertises', to='core.State'),
        ),
        migrations.AddField(
            model_name='adnational',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adnational_advertises', to='advertises.Banner', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='adcity',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adcity_advertises', to='advertises.Banner', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='adcity',
            name='cities',
            field=models.ManyToManyField(related_name='advertises', to='core.City'),
        ),
    ]
