# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-07 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcity',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adnational',
            name='title',
            field=models.CharField(default='AD Default', max_length=150, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adstate',
            name='title',
            field=models.CharField(default='ad', max_length=150, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
