# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-07 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertises', '0002_auto_20190307_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adcity',
            options={'verbose_name': 'Municipal', 'verbose_name_plural': 'Municipais'},
        ),
        migrations.AlterModelOptions(
            name='adnational',
            options={'verbose_name': 'Nacional', 'verbose_name_plural': 'Nacionais'},
        ),
        migrations.AlterModelOptions(
            name='adstate',
            options={'verbose_name': 'Estadual', 'verbose_name_plural': 'Estaduais'},
        ),
    ]
