# Generated by Django 2.2.7 on 2022-05-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertises', '0004_auto_20190319_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcity',
            name='cities',
            field=models.ManyToManyField(related_name='advertises', to='core.City', verbose_name='Municípios'),
        ),
        migrations.AlterField(
            model_name='adstate',
            name='states',
            field=models.ManyToManyField(related_name='advertises', to='core.State', verbose_name='Estados'),
        ),
    ]
