# Generated by Django 4.0.6 on 2022-07-12 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertises', '0005_auto_20220526_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcity',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_advertises', to='advertises.banner', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='adnational',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_advertises', to='advertises.banner', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='adstate',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_advertises', to='advertises.banner', verbose_name='Banner'),
        ),
    ]
