# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Preço'),
        ),
    ]
