# Generated by Django 2.2.7 on 2022-05-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20160327_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realty',
            options={'ordering': ['-created', '-modified', 'value'], 'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
    ]
