# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('max_mcmv', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Teto: Minha casa minha vida')),
                ('subsidy_max', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Subsídio máximo')),
                ('subsidy_min', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Subsídio mínimo')),
                ('multsub', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cidades',
                'ordering': ['name'],
                'verbose_name': 'Cidade',
                'permissions': (('view_city', 'Can view City'),),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=2, verbose_name='Sigla')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Estados',
                'ordering': ['name', 'abbr'],
                'verbose_name': 'Estado',
                'permissions': (('view_state', 'Can view State'),),
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.State', verbose_name='Estado'),
        ),
    ]
