# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160627_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='d_max_mcmv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Teto: Minha casa minha vida (c/ dependentes)'),
        ),
        migrations.AddField(
            model_name='city',
            name='d_multsub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='multsub (c/ dependentes)'),
        ),
        migrations.AddField(
            model_name='city',
            name='d_subsidy_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Subsídio máximo (c/ dependentes)'),
        ),
        migrations.AddField(
            model_name='city',
            name='d_subsidy_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Subsídio mínimo (c/ dependentes)'),
        ),
    ]
