# Generated by Django 2.2.7 on 2022-05-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180520_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name', 'abbr'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
    ]
