# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('localization', models.CharField(blank=True, max_length=150, verbose_name='Localização')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do catálogo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo?')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='core.City', verbose_name='Cidade')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='core.State', verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Catálogos',
                'verbose_name': 'Catálogo',
                'db_table': 'catalog',
            },
        ),
        migrations.CreateModel(
            name='CatalogPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('geral', 'Geral'), ('aluguel', 'Aluguel'), ('venda', 'Venda')], default='geral', max_length=7, verbose_name='Tipo')),
                ('number', models.CharField(max_length=15, verbose_name='Número')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='catalog.Catalog', verbose_name='Catálogo')),
            ],
            options={
                'verbose_name_plural': 'Números do catálogo',
                'verbose_name': 'Número do catálogo',
                'db_table': 'catalog_phone',
            },
        ),
        migrations.CreateModel(
            name='CatalogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('imobiliaria', 'Imobiliária'), ('correspondente', 'Correspondente Bancário'), ('incorporadora', 'Incorporadora')], max_length=25, verbose_name='Tipo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')),
            ],
            options={
                'verbose_name_plural': 'Tipos de catálogos',
                'verbose_name': 'Tipo de catálogo',
                'db_table': 'catalog_type',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Aguardando pagamento'), ('2', 'Em análise'), ('3', 'Paga'), ('4', 'Disponível'), ('5', 'Em disputa'), ('6', 'Devolvida'), ('7', 'Cancelada')], default='1', max_length=1)),
                ('transaction', models.CharField(blank=True, max_length=100)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='catalog.Catalog', verbose_name='Catálogo')),
            ],
            options={
                'verbose_name_plural': 'Histórico de pagamentos',
                'verbose_name': 'Histórico de pagamento',
                'db_table': 'payment_history',
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='catalog.CatalogType', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
